Define postmortems introduction
Jacob-Allebach/code-of-conduct pull request #12
Opened 2022-03-07 21:24 UTC by DlHolland

## Description

Added the postmortems introduction
### Type of Change

- [X] Feature
- [ ] Bug fix
- [ ] Documentation

## Contributors

- @DlHolland 

## Reminder

All GitHub Actions checks must be in a passing state in this branch or fork before this pull request can be merged.

2022-03-07 21:56 UTC, PaigeCD commented on conduct.md
> +Postmortems are evaluation of performances after implementation. The goal is to identify what worked and what didn't and describe what needed to be done differently. When a postmortem is done correct
In the first sentence "Postmortems are evaluation of performances", should this have been "are an evaluation" or "are evaluations" instead?

2022-03-07 21:57 UTC, PaigeCD commented on conduct.md
> +Postmortems are evaluation of performances after implementation. The goal is to identify what worked and what didn't and describe what needed to be done differently. When a postmortem is done correct
Perhaps "didn't" should be "did not".

2022-03-07 21:58 UTC, PaigeCD commented on conduct.md
> +Postmortems are evaluation of performances after implementation. The goal is to identify what worked and what didn't and describe what needed to be done differently. When a postmortem is done correct
In the last sentence, maybe add a comma between "done correctly" and "all team members".

2022-03-07 21:59 UTC, PaigeCD requested changes
The right sentiment is definitely there, but I have a few requested changes to polish it up!

2022-03-08 04:03 UTC, DlHolland commented
> The right sentiment is definitely there, but I have a few requested changes to polish it up!

Thanks for pointing those out!  I went ahead and made the changes.  If you see anything else that needs work let me know!

2022-03-08 04:12 UTC, mariakimheinert approved these changes
Looks good, @DlHolland! Thanks! :shipit:

2022-03-08 12:17 UTC, PaigeCD approved these changes
Looks great! Thanks! 👍

2022-03-08 16:22 UTC, merged